[package]
name = "rb_world"
version = "0.1.0"
edition = "2021"

[dependencies]
rb_core.workspace = true
rb_noise.workspace = true
bevy.workspace = true
serde.workspace = true
ron.workspace = true
pathfinding = "4.4"
rand = "0.8"
rand_chacha = "0.3"
