[package]
name = "rb_noise"
version = "0.1.0"
edition = "2021"

[dependencies]
rb_core.workspace = true
noise.workspace = true
bevy.workspace = true
rayon = "1.10"
smallvec = "1.13"

[dev-dependencies]
bevy.workspace = true

[[example]]
name = "noise_preview"
path = "examples/noise_preview.rs"
